### PR TITLE
Adding ACL token support

### PR DESCRIPTION
**Pull request by klangrudbke**
Great script!  My consul environment requires an ACL to backup and restore KV.  I added ACL token support if you wish to merge it.

### CODE REVIEW

**Comment by klangrudbke** [comment]
Can you take a look at this pull request?

**Comment by KyleJamesWalker** [comment]
Would love to see this ACL support added in!

**Comment by kailunshi** [comment]
sorry for the delay. i'll take a look at your PR and merge.

**Comment by KyleJamesWalker** [comment]
Thanks!

**Pull request merged**
